version: "3"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build:
      context: ../app/backend
    ports:
      - "8888:8888"
    environment:
      DB_HOST: db
    depends_on:
      - db

  frontend:
    build:
      context: ../app/frontend
    ports:
      - "5173:5173"
    environment:
      BACKEND_HOST: backend
    depends_on:
      - backend
